version: '3'
services:
  api:
    build: ./
    container_name: 'challenge-yana-api'
    volumes:
      - ./:/var/www/html
    ports:
      - "81:80"
    links:
      - db
      - cache
    environment:
      - TZ=America/Mexico_city
    depends_on:
      - db
      - cache
  db:
    container_name: 'challenge-db'
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    environment:
      MYSQL_DATABASE: yana
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: "123456789..."
      MYSQL_PASSWORD: "admin123#"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "33061:3306"
  cache:
    container_name: 'challenge-cache'
    image: redis
    ports:
      - "63791:6379"
volumes:
  db_data:

